### ISSUE TITLE
Hologram issue

### ISSUE THREAD

**Issue by DEADLYDEVIL-IR** [ZilloLP/CookieClicker#3]
Hi, can you add something to disable hologram for cookies and it'll also stops sending hologram related errors in the console

**Comment by ZilloLP** [comment]
Hey,
do I need to understand why you're opening an issue here when you've seen the thread where I write that I'm still fixing the problem? (https://gist.github.com/kloppie74/146e051253994f73a7134e4d7b75da78)
It also says that this error is only in 1.19.3.
The plugin is currently only programmed for 1.8 - 1.19.2 and therefore does not support 1.19.3.
And which hologram for cookies do you mean?

**Comment by DEADLYDEVIL-IR** [comment]
```
[19:21:52] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.network.protocol.game.PacketPlayOutSpawnEntity.<init>(net.minecraft.world.entity.EntityLiving)
[19:21:52] [Server thread/WARN]: 	at java.base/java.lang.Class.getConstructor0(Class.java:3585)
[19:21:52] [Server thread/WARN]: 	at java.base/java.lang.Class.getConstructor(Class.java:2271)
[19:21:52] [Server thread/WARN]: 	at CookieClicker.jar//de.zillolp.cookieclicker.utils.HologramUtil.createHologram(HologramUtil.java:153)
[19:21:52] [Server thread/WARN]: 	at CookieClicker.jar//de.zillolp.cookieclicker.utils.HologramUtil.spawn(HologramUtil.java:109)
[19:21:52] [Server thread/WARN]: 	at CookieClicker.jar//de.zillolp.cookieclicker.manager.PlayerManager.spawnHolograms(PlayerManager.java:50)
[19:21:52] [Server thread/WARN]: 	at CookieClicker.jar//de.zillolp.cookieclicker.listener.PlayerConnectionListener.onPlayerJoinEvent(PlayerConnectionListener.java:21)
[19:21:52] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor109.execute(Unknown Source)
[19:21:52] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[19:21:52] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[19:21:52] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:21:52] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672)
[19:21:52] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.a(PlayerList.java:319)
[19:21:52] [Server thread/WARN]: 	at net.minecraft.server.network.LoginListener.a(LoginListener.java:202)
[19:21:52] [Server thread/WARN]: 	at net.minecraft.server.network.LoginListener.d(LoginListener.java:183)
[19:21:52] [Server thread/WARN]: 	at net.minecraft.server.network.LoginListener.c(LoginListener.java:85)
[19:21:52] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:585)
[19:21:52] [Server thread/WARN]: 	at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:233)
[19:21:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1565)
[19:21:52] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:440)
[19:21:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[19:21:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[19:21:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[19:21:52] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[19:21:52] [Server thread/INFO]: [CookieClicker] [STDOUT] [CookieClicker] Error on creating the hologram
```

I mean the hologram whenever the plugin wants to create it above the cookie clicker block (/cookieclicker clicker ) and I know that it'll take time for it to get fixed but adding an option in 'config.yml' to disable holograms would be a temporary fix for it and it'll help to avoid spamming errors in the console for people who are using 1.19.3 lile me

**Comment by ZilloLP** [comment]
The plugin is programmed for 1.8 - 1.19.2.
This means that if you use it in 1.7 or 1.19.3 or 1.20, you cannot expect the plugin to work properly.
I just want to point this out again, because many people think that I have to fix this "problem" now, even though I don't want to/can't support this version at the moment.
I can/will add as last update that you can switch off the holograms, but there will be no more update where the "bug" is fixed, because it is currently too much work for me to fix this and I honestly don't want to support this version anymore.

I have decided to no longer support the plugin and to keep it up to date, as the compatibility for all versions limits me greatly, it only causes problems and I get more and more problems and hurdles to support it for the latest version, as you can see.
Therefore, I am currently working on a premium version, which only supports the latest version and thus has more new features and is generally completely new and better programmed. Therefore I would like to offer it as a premium resource.
