### ISSUE TITLE
Installed Cookieclicker 1.21.1 and then this with using MariaDB

### ISSUE THREAD

**Issue by Bensonheimer992** [ZilloLP/CookieClicker#4]
[00:46:22 WARN]: [CookieClicker] Plugin CookieClicker v5.1 - 1.21 generated an exception while executing task 1763
java.util.NoSuchElementException: decoder
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:302) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:290) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at CookieClicker.jar/de.zillolp.cookieclicker.listener.PacketReader.inject(PacketReader.java:49) ~[CookieClicker.jar:?]
        at CookieClicker.jar/de.zillolp.cookieclicker.manager.CookieClickerManager.registerPlayer(CookieClickerManager.java:52) ~[CookieClicker.jar:?]
        at CookieClicker.jar/de.zillolp.cookieclicker.manager.CookieClickerManager$1.run(CookieClickerManager.java:44) ~[CookieClicker.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by ZilloLP** [comment]
Hey, this is not an error message but a warning.
And this warning only appears because the plugin was not programmed for MariaDB but only for MySQL.
And I have decided to only support MySQL, as this is the database type that is used the most.
If you want to use MariaDB you can do that at your own risk, as far as I see it now it's just a warning that should have no effect on the function of the plugin, you can report it.
